MarkDown/第三章_深度学习基础.md
add one question in chapter3-3.12
=> add one question in chapter3-3.12

MarkDown/深度学习500问-Tan-08第八章 图像分割(md版本).md
作者：scutan90   
编辑者：shw2018（UESTC_孙洪卫_硕，Wechat: sunhwee）    
更新时间：2018.10.28
=> Update 第八章 图像分割

Translation Required
=> Translation Required

ch7_生成对抗网络(GAN)/ref.bib, ch7_生成对抗网络(GAN)/第七章_生成对抗网络(GAN).md
WIP, Init commit.
Some examples have not yet expanded.
Zehua Cheng
=> :tada: Add GAN. - Limber

ch7_生成对抗网络(GAN)/第七章_生成对抗网络(GAN).md
=> :sparkles: Fix some errors, add "Can GAN do ..."

ch15_GPU和框架选型/第十五章_异构运算、GPU及框架选型.md
刪除了 Windows 下產生的 CRLF 符號，修復了錯誤的 Ubuntu 拼寫，部分單詞大小寫調整.
如果可能的話，希望自薦一下自己寫的一個工具： [Tekorrect](https://github.com/n0vad3v/Tekorrect)，可以讓全書的排版更加規範一些.
=> 格式以及部分拼寫調整/修復.

ch09_图像分割/第九章_图像分割.md
=> 1.修复第九章中的格式问题

ch02_机器学习基础/第二章_机器学习基础.md
交叉熵代价函数(cross-entropy) 公式订正
#263
=> Update 第二章 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.20 EM 算法 公式修正

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.20 EM算法 公式修正

ch02_机器学习基础/第二章_机器学习基础.md
=> ROC曲线和PR曲线 图片标号

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.19.2 极大似然估计原理 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.18.7 常见的核函数有哪些 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
2.8.2 分类算法的评估方法 ROC曲线和PR曲线 内容修订
=> 2.8.2 分类算法的评估方法 ROC曲线和PR曲线 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.12.4 梯度下降法算法描述 内容修订 两段文字合并

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.16.11 ROC与AUC 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.12.7 各种梯度下降法性能比较 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.18.5 如何理解SVM中的对偶问题 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.16.1 模型评估常用方法？ 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
2.14.3 二类LDA算法原理？ 内容修订
向量加粗
y集合修正 为2分类
=> 2.14.3 二类LDA算法原理？ 内容修订

ch02_机器学习基础/第二章_机器学习基础.md
=> 2.14.3 二类LDA算法原理 内容修订

ch05_卷积神经网络(CNN)/第五章 卷积神经网络（CNN）.md
备注：一种局部特征聚合的池化方法NetVLAD，可以代替池化层使用的很好的方法
贡献人：熊楚原-中国人民大学
=> Update 第五章 卷积神经网络（CNN）.md

ch07_生成对抗网络(GAN)/ch7.md
Add 2019CVPR Paper and examples for GAN
=> Add 2019CVPR Paper and examples for GAN

English version/README.md
Change layout of README to make it easier to use for English-speakers and beginners.
Fix some grammar and spelling mistakes.
=> Update English version/README
